auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/ingress-nginx/controller: pangser/controller
  k8s.gcr.io/ingress-nginx/kube-webhook-certgen: pangser/kube-webhook-certgen
  
  
  
